(setq inhibit-startup-message t)
(global-font-lock-mode 't)
(setq visible-bell t)
(display-time)
(defalias 'yes-or-no-p 'y-or-n-p)
(blink-cursor-mode -1)
(column-number-mode 1)
(scroll-bar-mode -1)
(menu-bar-mode -1)
(tool-bar-mode -1)
(setq-default indent-tabs-mode nil)
(setq-default make-backup-files nil)