(setq inhibit-startup-message t)
(global-font-lock-mode 't)
(setq visible-bell t)
(display-time)
(defalias 'yes-or-no-p 'y-or-n-p)
(blink-cursor-mode 0)
(column-number-mode 1)
(if (functionp 'scroll-bar-mode) (scroll-bar-mode 0))
(if (functionp 'tool-bar-mode) (tool-bar-mode 0))
(if (functionp 'menu-bar-mode) (menu-bar-mode 0))
(setq-default indent-tabs-mode nil)
(setq-default make-backup-files nil)