{
    // Enforing
    "bitwise": false,
    "camelcase": false,
    "curly": false,
    "eqeqeq": true,
    "es5": false,
    "forin": false,
    "freeze": true,
    "immed": true,
    "indent": 2,
    "latedef": false,
    "newcap": true,
    "noarg": true,
    "noempty": true,
    //"nonew": true,
    "plusplus": false,
    "quotmark": true,
    "undef": true,
    "unused": true,
    "strict": false,
    "trailing": true,
    //"maxparams": 3,
    "maxdepth": 3,
    //"maxstatements": 4,
    //"maxcomplexity": 3,
    "maxlen": 80,

    // Relaxing
    "asi": false,
    "boss": false,
    "debug": false,
    "eqnull": false,
    "esnext": false,
    "evil": false,
    "expr": true,
    "funcscope": false,
    "globalstrict": false,
    "iterator": false,
    "lastsemic": true,
    "laxbreak": false,
    "laxcomma": false,
    "loopfunc": false,
    "moz": false,
    "multistr": false,
    "notypeof": false,
    "proto": false,
    //"scripturl": true,
    "smarttabs": false,
    "shadow": false,
    "sub": false,
    "supernew": false,
    
    // Environments
    "browser": true,
    "devel": false,
    "node": true,

    //Legacy
    "nomen": false,
    "onevar": false,
    "passfail": false,
    "white": true,

    // Undocumented
    "maxerr": 100,
    "predef": [
        "angular",
        "define",
        "module",
        "exports",
        "require",
        "seajs"
    ]
}
